#!/bin/bash

source ./colors

buyer_menu(){
        echo -ne "
$(magentaprint 'BUYER MENU')
$(greenprint '1)') View All Items
$(greenprint '2)') Purchase Items
$(greenprint '3)') View Purchase History
$(greenprint '4)') Back to Main Menu
$(greenprint '5)') Exit

Choose an option: "
        read -r opt
        case $opt in
        1)
                echo "view all items in store"
		python3 display_all
               	source ./buyerMenu #func name
                ;;
        2)
                echo "purchase items"
		python3 display_all
		python3 purchase
                source ./buyerMenu #func name
                ;;
        3)
                echo "view purchase history"
		python3 p_history
		source ./buyerMenu
                ;;
	4)
		echo "back to main menu"
		source ./mainMenu
		;;

        5)
                echo "Exit"
                exit 0
                ;;
        *)
                echo "Invalid Input"
                exit 1
                ;;
        esac
}



buyer_menu

