#!/bin/bash

source ./colors

seller_menu(){
        
    while [ 1 ]
    do

	echo -ne "
$(magentaprint 'SELLER MENU')
$(greenprint '1)') View All Items
$(greenprint '2)') Insert new item(s)
$(greenprint '3)') Change item id/name/price
$(greenprint '4)') Back to main menu
$(greenprint '5)') Exit

Choose an option: "
        read -N 10000000 -t 0.01
	read -r opt
        case $opt in
	1)
                echo "View All Items"
                python3 display_all.py
		
                ;;
	2)
                echo "Insert new item(s)"
		python3 populate.py
	
		;;
	3)
                echo "Change item id/name/price"
		python3 update_data.py
		
		;;
	4)
                echo "Back to main menu"
		source ./mainMenu
                ;;

	5)
                echo "Exit"
                exit 0
                ;;

	*)
		echo "Invalid input"
		exit 1
		;;
        
	esac
   done 
}




seller_menu

