#!/usr/bin/python3

import sqlite3

connection = sqlite3.connect("store.db")
cVar = connection.cursor()

def update_data():

    item = input("Choose an item to update: ")

    cVar.execute("SELECT * FROM store_items WHERE item_name = ?", (item,))
    data = cVar.fetchall()

    if len(data)==0:
            print('There is no item named %s'%item)
    else:
            print('Item %s found'%item)
            field = input("Choose one field to update (id/name/price): ")
            cVar.execute("UPDATE ")


